#define CMDN_AAA      "AAA    "
#define CMDN_AAD      "AAD    "
#define CMDN_AAM      "AAM    "
#define CMDN_AAS      "AAS    "
#define CMDN_ADC      "ADC    "
#define CMDN_ADD      "ADD    "
#define CMDN_AND      "AND    "
#define CMDN_ARPL     "ARPL   "
#define CMDN_BOUND    "BOUND  "
#define CMDN_BSF      "BSF    "
#define CMDN_BSR      "BSR    "
#define CMDN_BSWAP    "BSWAP  "
#define CMDN_BT       "BT     "
#define CMDN_BTC      "BTC    "
#define CMDN_BTR      "BTR    "
#define CMDN_BTS      "BTS    "
#define CMDN_CALL     "CALL   "
#define CMDN_CBW      "CBW    "
#define CMDN_CDQ      "CDQ    "
#define CMDN_CLC      "CLC    "
#define CMDN_CLD      "CLD    "
#define CMDN_CLI      "CLI    "
#define CMDN_CLTS     "CLTS   "
#define CMDN_CMC      "CMC    "
#define CMDN_CMP      "CMP    "
#define CMDN_CMPSB    "CMPSB  "
#define CMDN_CMPSW    "CMPSW  "
#define CMDN_CMPSD    "CMPSD  "
#define CMDN_CMPXCHG  "CMPXCHG"
#define CMDN_CWD      "CWD    "
#define CMDN_CWDE     "CWDE   "
#define CMDN_DAA      "DAA    "
#define CMDN_DAS      "DAS    "
#define CMDN_DEC      "DEC    "
#define CMDN_DIV      "DIV    "
#define CMDN_ENTER    "ENTER  "
#define CMDN_HLT      "HLT    "
#define CMDN_IDIV     "IDIV   "
#define CMDN_IMUL     "IMUL   "
#define CMDN_IN       "IN     "
#define CMDN_INC      "INC    "
#define CMDN_INSB     "INSB   "
#define CMDN_INSW     "INSW   "
#define CMDN_INSD     "INSD   "
#define CMDN_INT      "INT    "
#define CMDN_INTO     "INTO   "
#define CMDN_INVD     "INVD   "
#define CMDN_INLPG    "INLPG  "
#define CMDN_IRET     "IRET   "
#define CMDN_IRETD    "IRETD  "
#define CMDN_JO       "JO     "
#define CMDN_JNO      "JNO    "
#define CMDN_JB       "JB     "
#define CMDN_JAE      "JAE    "
#define CMDN_JZ       "JZ     "
#define CMDN_JNZ      "JNZ    "
#define CMDN_JBE      "JBE    "
#define CMDN_JA       "JA     "
#define CMDN_JS       "JS     "
#define CMDN_JNS      "JNS    "
#define CMDN_JPE      "JPE    "
#define CMDN_JPO      "JPO    "
#define CMDN_JL       "JL     "
#define CMDN_JGE      "JGE    "
#define CMDN_JLE      "JLE    "
#define CMDN_JG       "JG     "
#define CMDN_JMP      "JMP    "
#define CMDN_LAHF     "LAHF   "
#define CMDN_LAR      "LAR    "
#define CMDN_LEA      "LEA    "
#define CMDN_LEAVE    "LEAVE  "
#define CMDN_LGDT     "LGDT   "
#define CMDN_LIDT     "LIDT   "
#define CMDN_LGS      "LGS    "
#define CMDN_LSS      "LSS    "
#define CMDN_LFS      "LFS    "
#define CMDN_LDS      "LDS    "
#define CMDN_LES      "LES    "
#define CMDN_LLDT     "LLDT   "
#define CMDN_LMSW     "LMSW   "
#define CMDN_LOCK     "LOCK   "
#define CMDN_LODSB    "LODSB  "
#define CMDN_LODSW    "LODSW  "
#define CMDN_LODSD    "LODSD  "
#define CMDN_LOOP     "LOOP   "
#define CMDN_LOOPNZ   "LOOPNZ "
#define CMDN_LOOPZ    "LOOPZ  "
#define CMDN_LSL      "LSL    "
#define CMDN_LTR      "LTR    "
#define CMDN_MOV      "MOV    "
#define CMDN_MOVSB    "MOVSB  "
#define CMDN_MOVSW    "MOVSW  "
#define CMDN_MOVSD    "MOVSD  "
#define CMDN_MOVSX    "MOVSX  "
#define CMDN_MOVZX    "MOVZX  "
#define CMDN_MUL      "MUL    "
#define CMDN_NEG      "NEG    "
#define CMDN_NOP      "NOP    "
#define CMDN_NOT      "NOT    "
#define CMDN_OR       "OR     "
#define CMDN_OUT      "OUT    "
#define CMDN_OUTSB    "OUTSB  "
#define CMDN_OUTSW    "OUTSW  "
#define CMDN_OUTSD    "OUTSD  "
#define CMDN_POP      "POP    "
#define CMDN_POPA     "POPA   "
#define CMDN_POPAD    "POPAD  "
#define CMDN_POPF     "POPF   "
#define CMDN_POPFD    "POPFD  "
#define CMDN_PUSH     "PUSH   "
#define CMDN_PUSHA    "PUSHA  "
#define CMDN_PUSHAD   "PUSHAD "
#define CMDN_PUSHF    "PUSHF  "
#define CMDN_PUSHFD   "PUSHFD "
#define CMDN_RCL      "RCL    "
#define CMDN_RCR      "RCR    "
#define CMDN_ROL      "ROL    "
#define CMDN_ROR      "ROR    "
#define CMDN_REP      "REP    "
#define CMDN_REPZ     "REPZ   "
#define CMDN_REPNZ    "REPNZ  "
#define CMDN_RETN     "RETN   "
#define CMDN_SAHF     "SAHF   "
#define CMDN_SAL      "SAL    "
#define CMDN_SAR      "SAR    "
#define CMDN_SETO     "SETO   "
#define CMDN_SETNO    "SETNO  "
#define CMDN_SETB     "SETB   "
#define CMDN_SETAE    "SETAE  "
#define CMDN_SETZ     "SETZ   "
#define CMDN_SETNZ    "SETNZ  "
#define CMDN_SETBE    "SETBE  "
#define CMDN_SETA     "SETA   "
#define CMDN_SETS     "SETS   "
#define CMDN_SETNS    "SETNS  "
#define CMDN_SETPE    "SETPE  "
#define CMDN_SETPO    "SETPO  "
#define CMDN_SETL     "SETL   "
#define CMDN_SETGE    "SETGE  "
#define CMDN_SETLE    "SETLE  "
#define CMDN_SETG     "SETG   "
#define CMDN_SHL      "SHL    "
#define CMDN_SHR      "SHR    "
#define CMDN_SBB      "SBB    "
#define CMDN_SCASB    "SCASB  "
#define CMDN_SCASW    "SCASW  "
#define CMDN_SCASD    "SCASD  "
#define CMDN_SGDT     "SGDT   "
#define CMDN_SIDT     "SIDT   "
#define CMDN_SHLD     "SHLD   "
#define CMDN_SHRD     "SHRD   "
#define CMDN_SLDT     "SLDT   "
#define CMDN_SMSW     "SMSW   "
#define CMDN_STC      "STC    "
#define CMDN_STD      "STD    "
#define CMDN_STI      "STI    "
#define CMDN_STOSB    "STOSB  "
#define CMDN_STOSW    "STOSW  "
#define CMDN_STOSD    "STOSD  "
#define CMDN_STR      "STR    "
#define CMDN_SUB      "SUB    "
#define CMDN_TEST     "TEST   "
#define CMDN_VERR     "VERR   "
#define CMDN_VERW     "VERW   "
#define CMDN_WAIT     "WAIT   "
#define CMDN_WBINVD   "WBINVD "
#define CMDN_XADD     "XADD   "
#define CMDN_XCHG     "XCHG   "
#define CMDN_XLAT     "XLAT   "
#define CMDN_XOR      "XOR    "
#define CMDN_DB       "DB     "

#define CMDN_SEGES    "SEGES  "
#define CMDN_SEGCS    "SEGCS  "
#define CMDN_SEGSS    "SEGSS  "
#define CMDN_SEGDS    "SEGDS  "
#define CMDN_SEGFS    "SEGFS  "
#define CMDN_SEGGS    "SEGGS  "
#define CMDN_OPSIZE   "OPSIZE "
#define CMDN_ADDRSIZE "ADSIZE "
#define CMDN_RETF     "RETF   "
#define CMDN_JCXZ     "JCXZ   "
#define CMDN_JECXZ    "JECXZ  "
#define CMDN_LOADALL  "LOADALL"
#define CMDN_ESC      "ESC    "
#define CMDN_INVLPG   "INVLPG "

#define CMDN_FABS     "FABS   "
#define CMDN_FADD     "FADD   "
#define CMDN_FADDP    "FADDP  "
#define CMDN_FBLD     "FBLD   "
#define CMDN_FBSTP    "FBSTP  "
#define CMDN_FCHS     "FCHS   "
#define CMDN_FCLES    "FCLES  "
#define CMDN_FNCLEX   "FNCLEX "
#define CMDN_FCOM     "FCOM   "
#define CMDN_FCOMP    "FCOMP  "
#define CMDN_FCOMPP   "FCOMPP "
#define CMDN_FCOS     "FCOS   "
#define CMDN_FDECSTP  "FDECSTP"
#define CMDN_FDISI    "FDISI  "
#define CMDN_FNDISI   "FNDISI "
#define CMDN_FDIV     "FDIV   "
#define CMDN_FDIVP    "FDIVP  "
#define CMDN_FDIVR    "FDIVR  "
#define CMDN_FDIVRP   "FDIVRP "
#define CMDN_FENI     "FENI   "
#define CMDN_FNENI    "FNENI  "
#define CMDN_FFREE    "FFREE  "
#define CMDN_FIADD    "FIADD  "
#define CMDN_FICOM    "FICOM  "
#define CMDN_FICOMP   "FICOMP "
#define CMDN_FIDIV    "FIDIV  "
#define CMDN_FIDIVR   "FIDIVR "
#define CMDN_FILD     "FILD   "
#define CMDN_FIMUL    "FIMUL  "
#define CMDN_FINCSTP  "FINCSTP"
#define CMDN_FINIT    "FINIT  "
#define CMDN_FNINIT   "FNINIT "
#define CMDN_FIST     "FIST   "
#define CMDN_FISTP    "FISTP  "
#define CMDN_FISUB    "FISUB  "
#define CMDN_FISUBR   "FISUBR "
#define CMDN_FLD      "FLD    "
#define CMDN_FLDCW    "FLDCW  "
#define CMDN_FLDENV   "FLDENV "
#define CMDN_FLDLG2   "FLDLG2 "
#define CMDN_FLDLN2   "FLDLN2 "
#define CMDN_FLDL2E   "FLDL2E "
#define CMDN_FLDL2T   "FLDL2T "
#define CMDN_FLDPI    "FLDPI  "
#define CMDN_FLDZ     "FLDZ   "
#define CMDN_FLD1     "FLD1   "
#define CMDN_FMUL     "FMUL   "
#define CMDN_FMULP    "FMULP  "
#define CMDN_FNOP     "FNOP   "
#define CMDN_FPATAN   "FPATAN "
#define CMDN_FPREM    "FPREM  "
#define CMDN_FPREM1   "FPREM1 "
#define CMDN_FPTAN    "FPTAN  "
#define CMDN_FRNDINT  "FRNDINT"
#define CMDN_FRSTOR   "FRSTOR "
#define CMDN_FSAVE    "FSAVE  "
#define CMDN_FNSAVE   "FNSAVE "
#define CMDN_FSCALE   "FSCALE "
#define CMDN_FSETPM   "FSETPM "
#define CMDN_FSIN     "FSIN   "
#define CMDN_FSINCOS  "FSINCOS"
#define CMDN_FSQRT    "FSQRT  "
#define CMDN_FST      "FST    "
#define CMDN_FSTCW    "FSTCW  "
#define CMDN_FNSTCW   "FNSTCW "
#define CMDN_FSTENV   "FSTENV "
#define CMDN_FNSTENV  "FNSTENV"
#define CMDN_FSTP     "FSTP   "
#define CMDN_FSTSW    "FSTSW  "
#define CMDN_FNSTSW   "FNSTSW "
#define CMDN_FSUB     "FSUB   "
#define CMDN_FSUBP    "FSUBP  "
#define CMDN_FSUBR    "FSUBR  "
#define CMDN_FSUBRP   "FSUBRP "
#define CMDN_FTST     "FTST   "
#define CMDN_FUCOM    "FUCOM  "
#define CMDN_FUCOMP   "FUCOMP "
#define CMDN_FUCOMPP  "FUCOMPP"
#define CMDN_FWAIT    "FWAIT  "
#define CMDN_FXAM     "FXAM   "
#define CMDN_FXCH     "FXCH   "
#define CMDN_FXTRACT  "FXTRACT"
#define CMDN_FYL2X    "FYL2X  "
#define CMDN_FYL2XP1  "FYL2XP1"
#define CMDN_F2XM1    "F2XM1  "

#define CMD_AAA       0x00
#define CMD_AAD       0x01
#define CMD_AAM       0x02
#define CMD_AAS       0x03
#define CMD_ADC       0x04
#define CMD_ADD       0x05
#define CMD_AND       0x06
#define CMD_ARPL      0x07
#define CMD_BOUND     0x08
#define CMD_BSF       0x09
#define CMD_BSR       0x0A
#define CMD_BSWAP     0x0B
#define CMD_BT        0x0C
#define CMD_BTC       0x0D
#define CMD_BTR       0x0E
#define CMD_BTS       0x0F
#define CMD_CALL      0x10
#define CMD_CBW       0x11
#define CMD_CDQ       0x12
#define CMD_CLC       0x13
#define CMD_CLD       0x14
#define CMD_CLI       0x15
#define CMD_CLTS      0x16
#define CMD_CMC       0x17
#define CMD_CMP       0x18
#define CMD_CMPSB     0x19
#define CMD_CMPSW     0x1A
#define CMD_CMPSD     0x1B
#define CMD_CMPXCHG   0x1C
#define CMD_CWD       0x1D
#define CMD_CWDE      0x1E
#define CMD_DAA       0x1F
#define CMD_DAS       0x20
#define CMD_DEC       0x21
#define CMD_DIV       0x22
#define CMD_ENTER     0x23
#define CMD_HLT       0x24
#define CMD_IDIV      0x25
#define CMD_IMUL      0x26
#define CMD_IN        0x27
#define CMD_INC       0x28
#define CMD_INSB      0x29
#define CMD_INSW      0x2A
#define CMD_INSD      0x2B
#define CMD_INT       0x2C
#define CMD_INTO      0x2D
#define CMD_INVD      0x2E
#define CMD_INLPG     0x2F
#define CMD_IRET      0x30
#define CMD_IRETD     0x31
#define CMD_JO        0x32
#define CMD_JNO       0x33
#define CMD_JB        0x34
#define CMD_JAE       0x35
#define CMD_JZ        0x36
#define CMD_JNZ       0x37
#define CMD_JBE       0x38
#define CMD_JA        0x39
#define CMD_JS        0x3A
#define CMD_JNS       0x3B
#define CMD_JPE       0x3C
#define CMD_JPO       0x3D
#define CMD_JL        0x3E
#define CMD_JGE       0x3F
#define CMD_JLE       0x40
#define CMD_JG        0x41
#define CMD_JMP       0x42
#define CMD_LAHF      0x43
#define CMD_LAR       0x44
#define CMD_LEA       0x45
#define CMD_LEAVE     0x46
#define CMD_LGDT      0x47
#define CMD_LIDT      0x48
#define CMD_LGS       0x49
#define CMD_LSS       0x4A
#define CMD_LFS       0x4B
#define CMD_LDS       0x4C
#define CMD_LES       0x4D
#define CMD_LLDT      0x4E
#define CMD_LMSW      0x4F
#define CMD_LOCK      0x50
#define CMD_LODSB     0x51
#define CMD_LODSW     0x52
#define CMD_LODSD     0x53
#define CMD_LOOP      0x54
#define CMD_LOOPNZ    0x55
#define CMD_LOOPZ     0x56
#define CMD_LSL       0x57
#define CMD_LTR       0x58
#define CMD_MOV       0x59
#define CMD_MOVSB     0x5A
#define CMD_MOVSW     0x5B
#define CMD_MOVSD     0x5C
#define CMD_MOVSX     0x5D
#define CMD_MOVZX     0x5E
#define CMD_MUL       0x5F
#define CMD_NEG       0x60
#define CMD_NOP       0x61
#define CMD_NOT       0x62
#define CMD_OR        0x63
#define CMD_OUT       0x64
#define CMD_OUTSB     0x65
#define CMD_OUTSW     0x66
#define CMD_OUTSD     0x67
#define CMD_POP       0x68
#define CMD_POPA      0x69
#define CMD_POPAD     0x6A
#define CMD_POPF      0x6B
#define CMD_POPFD     0x6C
#define CMD_PUSH      0x6D
#define CMD_PUSHA     0x6E
#define CMD_PUSHAD    0x6F
#define CMD_PUSHF     0x70
#define CMD_PUSHFD    0x71
#define CMD_RCL       0x72
#define CMD_RCR       0x73
#define CMD_ROL       0x74
#define CMD_ROR       0x75
#define CMD_REP       0x76
#define CMD_REPZ      0x77
#define CMD_REPNZ     0x78
#define CMD_RETN      0x79
#define CMD_SAHF      0x7A
#define CMD_SAL       0x7B
#define CMD_SAR       0x7C
#define CMD_SETO      0x7D
#define CMD_SETNO     0x7E
#define CMD_SETB      0x7F
#define CMD_SETAE     0x80
#define CMD_SETZ      0x81
#define CMD_SETNZ     0x82
#define CMD_SETBE     0x83
#define CMD_SETA      0x84
#define CMD_SETS      0x85
#define CMD_SETNS     0x86
#define CMD_SETPE     0x87
#define CMD_SETPO     0x88
#define CMD_SETL      0x89
#define CMD_SETGE     0x8A
#define CMD_SETLE     0x8B
#define CMD_SETG      0x8C
#define CMD_SHL       0x8D
#define CMD_SHR       0x8E
#define CMD_SBB       0x8F
#define CMD_SCASB     0x90
#define CMD_SCASW     0x91
#define CMD_SCASD     0x92
#define CMD_SGDT      0x93
#define CMD_SIDT      0x94
#define CMD_SHLD      0x95
#define CMD_SHRD      0x96
#define CMD_SLDT      0x97
#define CMD_SMSW      0x98
#define CMD_STC       0x99
#define CMD_STD       0x9A
#define CMD_STI       0x9B
#define CMD_STOSB     0x9C
#define CMD_STOSW     0x9D
#define CMD_STOSD     0x9E
#define CMD_STR       0x9F
#define CMD_SUB       0xA0
#define CMD_TEST      0xA1
#define CMD_VERR      0xA2
#define CMD_VERW      0xA3
#define CMD_WAIT      0xA4
#define CMD_WBINVD    0xA5
#define CMD_XADD      0xA6
#define CMD_XCHG      0xA7
#define CMD_XLAT      0xA8
#define CMD_XOR       0xA9
#define CMD_DB        0xAA

#define CMD_FABS      0xAB
#define CMD_FADD      0xAC
#define CMD_FADDP     0xAD
#define CMD_FBLD      0xAE
#define CMD_FBSTP     0xAF
#define CMD_FCHS      0xB0
#define CMD_FCLES     0xB1
#define CMD_FNCLEX    0xB2
#define CMD_FCOM      0xB3  
#define CMD_FCOMP     0xB4
#define CMD_FCOMPP    0xB5
#define CMD_FCOS      0xB6  
#define CMD_FDECSTP   0xB7  
#define CMD_FDISI     0xB8  
#define CMD_FNDISI    0xB9  
#define CMD_FDIV      0xBA  
#define CMD_FDIVP     0xBB  
#define CMD_FDIVR     0xBC  
#define CMD_FDIVRP    0xBD
#define CMD_FENI      0xBE  
#define CMD_FNENI     0xBF  
#define CMD_FFREE     0xC0  
#define CMD_FIADD     0xC1  
#define CMD_FICOM     0xC2  
#define CMD_FICOMP    0xC3  
#define CMD_FIDIV     0xC4
#define CMD_FIDIVR    0xC5  
#define CMD_FILD      0xC6  
#define CMD_FIMUL     0xC7
#define CMD_FINCSTP   0xC8
#define CMD_FINIT     0xC9  
#define CMD_FNINIT    0xCA  
#define CMD_FIST      0xCB  
#define CMD_FISTP     0xCC  
#define CMD_FISUB     0xCD  
#define CMD_FISUBR    0xCE  
#define CMD_FLD       0xCF  
#define CMD_FLDCW     0xD0
#define CMD_FLDENV    0xD1  
#define CMD_FLDLG2    0xD2  
#define CMD_FLDLN2    0xD3  
#define CMD_FLDL2E    0xD4  
#define CMD_FLDL2T    0xD5  
#define CMD_FLDPI     0xD6
#define CMD_FLDZ      0xD7  
#define CMD_FLD1      0xD8  
#define CMD_FMUL      0xD9  
#define CMD_FMULP     0xDA
#define CMD_FNOP      0xDB
#define CMD_FPATAN    0xDC  
#define CMD_FPREM     0xDD  
#define CMD_FPREM1    0xDE  
#define CMD_FPTAN     0xDF  
#define CMD_FRNDINT   0xE0  
#define CMD_FRSTOR    0xE1  
#define CMD_FSAVE     0xE2  
#define CMD_FNSAVE    0xE3
#define CMD_FSCALE    0xE4  
#define CMD_FSETPM    0xE5  
#define CMD_FSIN      0xE6  
#define CMD_FSINCOS   0xE7  
#define CMD_FSQRT     0xE8
#define CMD_FST       0xE9  
#define CMD_FSTCW     0xEA  
#define CMD_FNSTCW    0xEB  
#define CMD_FSTENV    0xEC  
#define CMD_FNSTENV   0xED
#define CMD_FSTP      0xEE
#define CMD_FSTSW     0xEF  
#define CMD_FNSTSW    0xF0  
#define CMD_FSUB      0xF1  
#define CMD_FSUBP     0xF2  
#define CMD_FSUBR     0xF3  
#define CMD_FSUBRP    0xF4
#define CMD_FTST      0xF5
#define CMD_FUCOM     0xF6
#define CMD_FUCOMP    0xF7
#define CMD_FUCOMPP   0xF8
#define CMD_FWAIT     0xF9
#define CMD_FXAM      0xFA
#define CMD_FXCH      0xFB
#define CMD_FXTRACT   0xFC
#define CMD_FYL2X     0xFD
#define CMD_FYL2XP1   0xFE
#define CMD_F2XM1     0xFF

#define CMD_SEGES     0x100
#define CMD_SEGCS     0x101
#define CMD_SEGSS     0x102
#define CMD_SEGDS     0x103
#define CMD_SEGFS     0x104
#define CMD_SEGGS     0x105
#define CMD_OPSIZE    0x106
#define CMD_ADDRSIZE  0x107
#define CMD_RETF      0x108
#define CMD_JCXZ      0x109
#define CMD_JECXZ     0x10A
#define CMD_LOADALL   0x10B
#define CMD_ESC       0x10C
